---
title: My CTF Blog
description: My ctf journey and writeups
theme: minima
plugins:
  - jekyll-feed
include:
  - _includes

defaults:
  - scope:
      path: "about.md"
    values:
      layout: "default"
      custom_css: true
---

