title: Cybersecurity
description: CTFs, notes, CVEs, and writeups related to cybersecurity.
url: https://pathogenickatt.github.io 
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

future: true

# Sass configuration to suppress deprecation warnings
sass:
  quiet_deps: true
  style: compressed

collections:
  notes:
    output: true
    permalink: /notes/:path/
    sort_by: date
    sort_order: ascending
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:slug/
  writeups:
    output: true
    permalink: /writeups/:name/
    sort_by: date
    sort_order: descending
    publish: true
  cves:
    output: true
    permalink: /cves/:name/
  

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      custom_css: true
  - scope:
      path: "_notes"
    values:
      layout: "note"
  - scope:
      path: "_posts"
    values:
      layout: "post"
  - scope:
      path: "_writeups"
    values:
      layout: "writeup"

include:
  - _notes
  - _includes
  - _layouts
  - assets/css
  - assets/js

