---
title: My CTF Blog
description: My ctf journey and writeups
theme: minima
plugins:
  - jekyll-feed


defaults:
  - scope:
      path: "about.md"
    values:
      layout: "default"
      custom_css: true
---

include:
  - _includes
  - _layouts
  - assets/css
  - assets/js